### ISSUE TITLE
USAGE - Instructions 

### ISSUE THREAD

**Issue by future2back** [ruangustavo/Kwai-Watcher#1]
Hello, thanks for sharing it.

Are you using it with emulator or what?
Could you explain me please?
thank you.
🙏🏻

**Comment by ruangustavo** [comment]
Hey, no problem!

Yes, I'm using an emulator. Specifically, multi-drive from Nox so that I'd can open multiple emulators at the same time. Besides that, you can use Nox, Memu, Bluestacks... Whatever you want :)
